image: ubuntu:latest

stages:
    - deploy

pages:
    stage: deploy
    script:
        - apt update && apt install -y python3 python3-pip
        - python3 -m pip install pandas
        - python3 create_json.py
        - ls
        - rm -rf public
        - mkdir -p public/
        - cp -r *.html public/
        - cp -r js/ public/
        - cp -r js_data/ public/
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - master
