image: ghcr.io/ricosjp/allgebra/cuda10_2/gcc10/mkl:20.12.1

stages:
    - deploy

pages:
    stage: deploy
    script:
        - python3 create_json.py
        - ls
        - rm -rf public
        - mkdir -p public/
        - cp -r *.html public/
        - cp -r js/ public/
        - cp -r js_data/ public/
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - master
