image: ghcr.io/ricosjp/allgebra/cuda10_2/mkl:20.10.1

stages:
    - create_json
    - deploy

create_json_py:
    stage: create_json
    script:
        - python3 create_json.py
    artifacts:
        paths:
            - json_data/
        expire_in: 20min

pages:
    stage: deploy
    script:
        - rm -rf public html
        - mkdir -p public
        - cp 0r *.html public
        - cp -r *.js public
        - cp -r create_json public
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - master
