image: ghcr.io/ricosjp/allgebra/cuda10_2/mkl:20.10.1

stages:
    - deploy

benchmark_page:
    stage: deploy
    script:
        - python3 create_json.py
        - rm -rf public html
        - mkdir -p public
        - cp -r *.html public
        - cp -r *.js public
        - cp -r json_data/ public
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - master
