image: ghcr.io/ricosjp/allgebra/cuda10_2/mkl:20.10.1

stages:
    - create_json
    - deploy

json:
    stage: create_json
    script:
        - python3 create_json.py
    artifacts:
        paths:
            - js_data
        expire_in: 20min
    only:
        - master


benchmark_page:
    stage: deploy
    script:
        - rm -rf public html
        - mkdir -p public/
        - cp -r *.html public/
        - cp -r *.js public/
        - cp -r js_data/ public/
    artifacts:
        paths:
            - public
        expire_in: 20min
    only:
        - master
